/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import org.assertj.core.api.SoftAssertions;
import org.junit.Test;

import java.util.Collections;
import java.util.Random;

import static org.assertj.core.api.Assertions.assertThat;


public class AppTest {
    @Test
    public void testCollectionsAddAll() {
        DIYArrayList<Integer> testList = new DIYArrayList<>();
        Collections.addAll(testList, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21);

        /*
        Array is not empty and filled up with ints
        Array size is equal to elements count
        */

        SoftAssertions softly = new SoftAssertions();
        softly.assertThat(testList).isNotNull();
        softly.assertThat(testList.size()).isEqualTo(21);
    }

    @Test
    public void testCollectionsCopy() {
        DIYArrayList<Integer> listFrom = new DIYArrayList<>();
        DIYArrayList<Integer> listTo = new DIYArrayList<>();

        for (int i = 0; i < 25; i++) {
            listTo.add(i);
        }

        listFrom.add(999);
        Collections.copy(listTo, listFrom);

        /*
        Array is created
        Array size not changed
        Array is modified by copy method
        */
        SoftAssertions softly = new SoftAssertions();
        softly.assertThat(listTo).isNotNull();
        softly.assertThat(listTo.size()).isEqualTo(25);
        softly.assertThat(listTo.get(0)).isEqualTo(999);
    }

    @Test
    public void testCollectionsSort() {
        DIYArrayList<Integer> testList = new DIYArrayList<>();
        Random rand = new Random();

        for (int j = 0; j < 25; j++) {
            testList.add(rand.nextInt(100));
        }

        Collections.sort(testList);
        // Array is sorted
        assertThat(testList).isSorted();
    }
}
